name: Deploy JFinanceiro

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Instalar dependências PHP
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências Node
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Copiar arquivos para servidor
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/home1/jfinan85/jfinanceiro.com.br"

          rm: false
          overwrite: true

          strip_components: 0

          exclude: |
            .git
            .github
            node_modules
            tests
            storage/logs
            storage/framework/cache
            storage/framework/sessions
            storage/framework/views
            .env

      - name: Executar comandos Laravel
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home1/jfinan85/jfinanceiro.com.br

            /opt/cpanel/composer/bin/composer install \
              --no-dev \
              --prefer-dist \
              --optimize-autoloader

            php artisan optimize:clear

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            php artisan optimize